### ISSUE TITLE
NetCDF4 unavailable on Orion

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [NOAA-EMC/EMC_verif-global#101]
It seems that the NetCDF4 module has been removed from intelpython3/2020 (and intelpython3/2020.2) on Orion.  When running verif-global standalone, I am receiving errors that it cannot be loaded.  Loading the module from bash and executing `conda list -n <all_envs> | grep -i netcdf` verifies that it is not available.  Perhaps another Python module should be loaded or it should be added to that distribution.

**Comment by malloryprow** [comment]
@DavidHuber-NOAA That is frustrating it was removed! Have you looked around at any of the other python modules on Orion to see if they are available?

**Comment by DavidHuber-NOAA** [comment]
Yes, python/3.7.5 has it, though metplus still requires the intelpython3/2020 module be loaded.  My workaround is to add
`module load python/3.7.5` 
to load_modules.sh after
`module load emc_verif_global_orion`
This is a little ugly, but it works.  Perhaps this could be rectified by modifying the metplus modulefile to allow different python modules.

**Comment by malloryprow** [comment]
Glad you found a workaround! I have the METplus Users Workshop today through Wednesday. I'll see if I can get the workaround included in the develop branch late this week/next week. I'm not sure if the module files can be adjusted. I think MET was built using the intelpython3/2020.

**Comment by malloryprow** [comment]
@DavidHuber-NOAA Changes merged into develop branch

**Comment by DavidHuber-NOAA** [comment]
Thanks!
