### ISSUE TITLE
Updated verif fix locations

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [NOAA-EMC/EMC_verif-global#108]
The fix files on the RDHPCS machines have changed locations and should be updated in set_up_verif_global.sh.  I believe they should be changed from
$GLOPARA/fix/fix_verif
to
$GLOPARA/fix/verif/20220805

**Comment by malloryprow** [comment]
Thanks David! Do you want to do the changes and submit a PR?

**Comment by malloryprow** [comment]
@DavidHuber-NOAA  Yes, the are!

**Comment by KateFriedman-NOAA** [comment]
@DavidHuber-NOAA @malloryprow I actually moved them to `/lfs/h2/emc/global/noscrub/emc.global/FIX/fix/verif/20220805` (`save` -> `noscrub`) with a symlink to redirect from `save` to `noscrub`. Mind updating that for WCOSS2 in this? Thanks!

**Comment by DavidHuber-NOAA** [comment]
@KateFriedman-NOAA You got it!
