### ISSUE TITLE
Update Jet support

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [NOAA-EMC/EMC_verif-global#110]
A Jet module file should be created and all components re-tested to verify they still work on the system.  Similarly, the modules should all be pointed towards the EPIC hpc-stack builds.  First, MET and METplus need to be installed in that hpc-stack distribution.

**Comment by malloryprow** [comment]
@DavidHuber-NOAA Is there are plan for MET and METplus to be installed in the hpc-stack?

**Comment by DavidHuber-NOAA** [comment]
@malloryprow It is available to be installed and newer versions of MET/METplus (10.1.2/4.1.3) have already been installed on Hera and Orion (I believe to support UFS SRW validation).  For Jet, it's desired because the current installations in /contrib use older dependencies, making it difficult to play nicely with the workflow.

**Comment by DavidHuber-NOAA** [comment]
@malloryprow Those versions aren't installed yet, but I have requested them.  And thank you for the info RE EVS!  That's very good to know that a followup system is in the works.

**Comment by malloryprow** [comment]
Great, I'm heading out for the day soon, but will check it out tomorrow morning. Thought I have on my calendar there is a Jet Outage tomorrow? Not sure if you want me to check any output or anything or if you feel the output from https://github.com/NOAA-EMC/global-workflow/pull/1301 suffices.

**Comment by DavidHuber-NOAA** [comment]
The logs do have a few messages in them that might be worth checking out, though they don't seem to affect the outcomes.  I've pushed the logs over to Hera (/scratch1/NESDIS/nesdis-rdo2/David.Huber/para/com/jet_tc_192_logs/*/gfsmetp*).  It looks like there may be a bug in run_verif_global_in_global_workflow.sh.  There are a few places (e.g. [line 145](https://github.com/NOAA-EMC/EMC_verif-global/blob/5dcb84ab048e757b155c17e4f87d960b31aa695d/ush/run_verif_global_in_global_workflow.sh#L145)) where `SDATE_GFS_YYYYMMDDHH` is not in the expected format (`2022-04-01` instead of `2022040100`, for instance).
