### ISSUE TITLE
Upgrade to spack-stack 1.6.0 for running in global-workflow

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [NOAA-EMC/EMC_verif-global#117]
EMC_Verif-Global should be upgraded to use the newest suite of spack-stack libraries (version 1.6.0). This includes an upgrade of netcdf-fortran to 4.6.1, prod_util to 2.1.1, and Python to 3.11.6.  This should resolve at least some of the issues seen in the global-workflow.

**Comment by malloryprow** [comment]
Thanks! The module loading will take place within the global-workflow, but I know a few places things will need to be update in EMC_verif-global to make sure we have things set up correctly.

**Comment by malloryprow** [comment]
Changing issue name from "Upgrade to spack-stack 1.6.0" to "Upgrade to spack-stack 1.6.0 for running in global-workflow". 

spack-stack v1.6.0 gsi-addon-dev has the need python, MET, and METplus versions needed to run EMC_verif-global for generating stats (which is what runs in the global-workflow)

Plots needs matplotlib and cartopy which are currently only in unified-env, and unified-env has the wrong versions of MET, METplus, and python that are needed, so plots cannot be generated using spack-stack v1.6.0.

EMC_verif-global standalone will update to using the spack-stack modules in the next spack-stack release (June-July timeframe), but the work to using the spack-stack module within the global-workflow can proceed.

**Comment by malloryprow** [comment]
Noting, that the completion of this work will allow https://github.com/NOAA-EMC/EMC_verif-global/issues/92 to be closed
