### ISSUE TITLE
Update Orion modulefile after Rocky 8 upgrade

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/EMC_verif-global#127]
Does the Orion modulefile need to be updated after the upgrade to Rocky8?
If not, then this issue can be closed.

**Comment by malloryprow** [comment]
I believe it may be. The person doing the installations at DTC is going to look at things next week. If the installations need to be recompiled and different pre-req modules need to be loaded, I'll update modulefiles/emc_verif_global_orion.lua accordingly and test. This would only impact when running it standalone/outside of the global-workflow. The module loading for the global-workflow all comes from there.

**Comment by malloryprow** [comment]
So I'm going to leave the issue open for now.

**Comment by aerorahul** [comment]
Thanks for the note @malloryprow

**Comment by malloryprow** [comment]
I have updated [emc_verif_global_orion.lua](https://github.com/NOAA-EMC/EMC_verif-global/blob/orion_rocky8/modulefiles/emc_verif_global_orion.lua) for Rocky 8. I did a few quick tests for the stats and plots running EMC_verif-global standalone.I'm going to merge [orion_rocky8](https://github.com/NOAA-EMC/EMC_verif-global/tree/orion_rocky8) into the develop branch and close this issue.

The module loading related to global-workflow all resides in there. When the time comes that that is being tested and there are problems we can open new issues as needed.

Sound good @aerorahul?

**Comment by malloryprow** [comment]
Done in https://github.com/NOAA-EMC/EMC_verif-global/commit/df296f4204e05abdced9cb7265e62bc1020e93b2

**Comment by aerorahul** [comment]
Thanks for the work @malloryprow.  Much appreciated!
We need to update the hash in the global-workflow.  @KateFriedman-NOAA can you please take note and make a PR.

**Comment by KateFriedman-NOAA** [comment]
@aerorahul Note made in https://github.com/NOAA-EMC/global-workflow/issues/2694. Will open PR to update to new hash.
