### ISSUE TITLE
Update nproc for global-workflow

### ISSUE THREAD

**Issue by malloryprow** [NOAA-EMC/EMC_verif-global#129]
In https://github.com/NOAA-EMC/EMC_verif-global/blob/develop/ush/run_verif_global_in_global_workflow.sh, change line 252 `export nproc=${npe_metp:-1}` to `export nproc=${nproc:-1}`.

@DavidHuber-NOAA please confirm this is the desired change.

**Comment by DavidHuber-NOAA** [comment]
Yes, that's correct.  Thanks!

**Comment by malloryprow** [comment]
Done in https://github.com/NOAA-EMC/EMC_verif-global/commit/0d9e0b6ab0cabbaccbdfa0868a256065984777ee
