### ISSUE TITLE
Running as part of global-workflow fails in exgrid2grid_step2.sh with srun: no record for task id 1

### ISSUE THREAD

**Issue by DWesl** [NOAA-EMC/EMC_verif-global#133]
Running for a C768 run as part of global-workflow produces a specification with `nodes=1`, `ppn=4`, and `tpp=1`.
Running with `ush/run_verif_global_in_global_workflow.sh` produces a job with `nproc=${npe_node_metp_gfs}=1`.
When run on HERA, `scripts/exgrid2grid_step1.sh` launches the METplus job with `srun --multi-prog /path/to/task-file`, where `task-file` has `nproc` lines detailing commands to execute.  `srun` then fails because it can't find as many tasks as it wants; I think it is defaulting to four tasks.

Changing `scripts/exgrid2grid_step1.sh` to specify `--ntasks ${nproc}` as part of the `srun` command allows the process to finish.  A better solution probably involves changing how `ush/run_verif_global_in_global_workflow.sh` determines `nproc`: `man sbatch` suggests `SLURM_NTASKS`, but `global-workflow` probably has a variable to specify the number of threads that would be less closely tied to the job manager.

**Comment by DavidHuber-NOAA** [comment]
@DWesl This was recently fixed in the global-workflow as part of an overhaul of the resource configuration system.  The job now runs with a single task by default.  See https://github.com/NOAA-EMC/global-workflow/pull/2804 and let me know if updating your global-workflow resolves the issue.

**Comment by DWesl** [comment]
The new setting in verif-global (should have checked this earlier) references `nproc` and defaults to one:
https://github.com/NOAA-EMC/EMC_verif-global/blob/92904d2c431969345968f74e676717057ec0042a/ush/run_verif_global_in_global_workflow.sh#L277-L279
and global-workflow [sets `nproc` in config.metp](https://github.com/NOAA-EMC/global-workflow/blob/66fc89ccd27d7ad35d85b447c703fba26f9f419f/parm/config/gfs/config.metp#L11), which should solve the problem more generally.
