### ISSUE TITLE
Update EMC_verif-global to run on Gaea-C5

### ISSUE THREAD

**Issue by DavidBurrows-NCO** [NOAA-EMC/EMC_verif-global#136]
Update scripts in the EMC_verif-global package to run on Gaea-C5 to eventually run as part of the global workflow.

**Comment by DavidBurrows-NCO** [comment]
Hi @malloryprow I am working on porting EMC_verif-global to Gaea-C5 in support of PSL/GSL/EPIC atmospheric rivers project.  I see your name in many of the paths in `verif-global.fd/ush/run_verif_global_in_global_workflow.sh`.  I'm wondering if you could provide some information about porting to a new system or point me in the right direction. Thanks in advance.

**Comment by malloryprow** [comment]
You'll need to make sure the necessary libraries are installed and there will be to be archive for prepbufr data for the grid2obs verification and 24 hour CCPA data for the precipitation verification.

My new role at work is no longer global verification. I'm still tasked with supporting global verification until a new hire is on an trained, so I can't say how much time I can provide with assisting with this port.

**Comment by DavidBurrows-NCO** [comment]
@malloryprow Thank you for the information. I was able to transfer ccpa and prepbufr data from Hera to Gaea-C5. I will work on running EMC_verif-global on C5 and submit the appropriate PRs. Thanks again.
