### ISSUE TITLE
Fix bug in plotting of confidence interval bars in mean plots

### ISSUE THREAD

**Issue by malloryprow** [NOAA-EMC/EMC_verif-global#32]
There is a bug in the plots for the mean related plots (plot_lead_mean.py and plot_threshold_mean.py) related to getting the bars of the confidence intervals plotted. This bug was discovered on Hera because it causes the scripts to fail, but oddly the scripts run just fine on WCOSS!

This will result a new tag verif_global_v1.13.5. 

@KateFriedman-NOAA, since this is plotting related and this doesn't run in the global workflow the checkout of this tag isn't critical, but we can update it if you would like, but not a priority.

**Comment by KateFriedman-NOAA** [comment]
@malloryprow Gotcha. Is this plotting something that global-workflow users may do offline with their outputted METplus data? If so, I'll update to this tag right away. If not, I'll wait for the next tag, I know you have some updates coming down the line that we'll want. Thanks!

**Comment by malloryprow** [comment]
@KateFriedman-NOAA It is plotting they can do offline with their METplus output. Tag should be ready by end of today or Monday! I'll keep you in the loop.

**Comment by malloryprow** [comment]
Work being done in https://github.com/NOAA-EMC/EMC_verif-global/tree/hotfix_fix_ci_bars

Testing passed on WCOSS.

**Comment by malloryprow** [comment]
Testing passed on Hera.

**Comment by malloryprow** [comment]
Merged into master at https://github.com/NOAA-EMC/EMC_verif-global/commit/4522b2d85279819a74958de7007532ff25b76b02

Merged into develop at https://github.com/NOAA-EMC/EMC_verif-global/commit/5c45f202117eb40bf1dfdd1dbb7c97ef00b3fda9

Tag verif_global_v1.13.5 created.

@KateFriedman-NOAA, verif_global_v1.13.5 is ready to go for the workflow! :)

**Comment by KateFriedman-NOAA** [comment]
Thanks @malloryprow !
