### ISSUE TITLE
build_webpage.py fails on Hera

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/EMC_verif-global#88]
While it is possible to execute ssh commands from Hera to emcrzdm, `ush/build_wepage.py` contains the following logic prevents transfers from Hera to emcrzdm.
```
elif machine in ['HERA', 'JET']:
    if webhost == 'emcrzdm.ncep.noaa.gov':
        print("ERROR: Currently "+machine.title()+" cannot connect to "
              +webhost)
```

Below is an example of what the above logic generates on Hera.
```
BEGIN: build_webpage.py
Webhost: emcrzdm.ncep.noaa.gov
Webhost location: /home/people/emc/www/htdocs/gmb/wd20rt/metplus/v153rt1

Total images in /scratch1/NCEPDEV/stmp2/Russ.Treadon/verif_global_standalone/tmpnwdev/verif_global.232018/grid2grid_step2/metplus_output/images: 33649
Submitting /scratch1/NCEPDEV/stmp2/Russ.Treadon/verif_global_standalone/tmpnwdev/verif_global.232018/batch_jobs/verif_global_grid2grid_step2_web.sh to service
Output sent to https://www.emc.ncep.noaa.gov/gmb/wd20rt/metplus/v153rt1//scratch1/NCEPDEV/stmp2/Russ.Treadon/verif_global_standalone/tmpnwdev/verif_global.232018/batch_jobs/verif_global_grid2grid_step2_web.out
ERROR: Currently Hera cannot connect to emcrzdm.ncep.noaa.gov
END: build_webpage.py
```

Manually executing `verif_global_grid2grid_step2_web.sh` from a Hera PuTTY window successfully transferred files to [https://www.emc.ncep.noaa.gov/gmb/wd20rt/metplus/v153rt1/](https://www.emc.ncep.noaa.gov/gmb/wd20rt/metplus/v153rt1/).

Since METplus is the official verification package for EMC and many developers use Hera for global parallels, it would be good to update `ush/build_page.py` so that it can transfer METplus plots from Hera to emcrzdm.

**Comment by malloryprow** [comment]
@RussTreadon-NOAA Thanks for bringing this up! Last time I had tried, which I will admit was a long time ago, I couldn't connect to emcrzdm from Hera. This is a simple fix I can have done by today and into the develop branch.

**Comment by malloryprow** [comment]
@RussTreadon-NOAA The develop branch has the changes in it!

**Comment by RussTreadon-NOAA** [comment]
Thank you, @malloryprow , for the quick action.   

I checked out [develop](https://github.com/NOAA-EMC/EMC_verif-global/tree/develop) at 0217d45 and reran the METplus plotting job on Hera.   `ush/build_webpage.py` submitted the grid2grid and scorecard web jobs.  Both jobs ran and uploaded images to [https://www.emc.ncep.noaa.gov/gmb/wd20rt/metplus/v153rt1/](https://www.emc.ncep.noaa.gov/gmb/wd20rt/metplus/v153rt1/).

A check of `/scratch1/NCEPDEV/stmp2/Russ.Treadon/verif_global_standalone/tmpnwdev/verif_global.228291/batch_jobs/verif_global_grid2grid_step2.out` shows the following error message
```
+ python /scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/develop/sorc/verif-global.fd/ush/build_webpage.py
Submitted batch job 27928853
--- Logging error ---
Traceback (most recent call last):
  File "/contrib/anaconda/anaconda3/latest/lib/python3.7/logging/handlers.py", line 939, in emit
    self.socket.sendto(msg, self.address)
OSError: [Errno 101] Network is unreachable

...

  File "/contrib/anaconda/anaconda3/latest/lib/python3.7/site-packages/sitecustomize.py", line 537, in output_depends
    logger.info(message)
Message: "((('/scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/develop/sorc/verif-global.fd/ush', 'build_webpage.py'), ('/scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/develop/sorc/verif-global.fd/ush', 'get_tc_info.py')))"
Arguments: ()
--- Logging error ---

...

Message: "((('/scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/develop/sorc/verif-global.fd/ush', 'get_tc_info.py'), ('/contrib/anaconda/anaconda3/latest/lib/python3.7/site-packages', 'pandas')))"
Arguments: ()
BEGIN: build_webpage.py
Webhost: emcrzdm.ncep.noaa.gov
Webhost location: /home/people/emc/www/htdocs/gmb/wd20rt/metplus/v153rt1

Total images in /scratch1/NCEPDEV/stmp2/Russ.Treadon/verif_global_standalone/tmpnwdev/verif_global.228291/grid2grid_step2/metplus_output/images: 33649
Submitting /scratch1/NCEPDEV/stmp2/Russ.Treadon/verif_global_standalone/tmpnwdev/verif_global.228291/batch_jobs/verif_global_grid2grid_step2_web.sh to service
Output sent to /scratch1/NCEPDEV/stmp2/Russ.Treadon/verif_global_standalone/tmpnwdev/verif_global.228291/batch_jobs/verif_global_grid2grid_step2_web.out
END: build_webpage.py
+ status=0
```
So while plots made it to emcrzdm, is everything OK on Hera?

**Comment by malloryprow** [comment]
@RussTreadon-NOAA Everything is okay on Hera. I have seen that message for as long as I can remember on Hera, but it doesn't actually impact anything and I'm not sure exactly the source or how to fix it.

**Comment by RussTreadon-NOAA** [comment]
OK.   Then it seems this issue can be closed.   Thanks again, @malloryprow
