### ISSUE TITLE
MET+ fails on Hera due to removed modules

### ISSUE THREAD

**Issue by WalterKolczynski-NOAA** [NOAA-EMC/EMC_verif-global#89]
MET+ jobs in global-workflow are now failing at runtime on Hera due to an update to lmod that makes prod_util/1.1.0 and other modules unavailable. The module versions need to be updated to ones that are available.

**Comment by malloryprow** [comment]
@WalterKolczynski-NOAA Can you please specify all the modules?

**Comment by WalterKolczynski-NOAA** [comment]
It dies after the first failed load, but reportedly anything in `/scratch2/NCEPDEV/nwprod/NCEPLIBS/modulefiles`

Really all the modules should updated to use the hpc-stack installation (on all machines), and it sounds like the NCEPLIBS modules are going to be outright removed soon.

**Comment by malloryprow** [comment]
@WalterKolczynski-NOAA I updated the module loading for EMC_verif-global. I can confirm it has loaded without issues running standalone. Would you like to checkout the hotfix branch (hotfix_hera_modules) and test in the global workflow before I cut the tag?

**Comment by WalterKolczynski-NOAA** [comment]
Looks like that works.

**Comment by malloryprow** [comment]
Great. Tag with the hotfix is verif_global_v2.8.2.
