### ISSUE TITLE
Verify should exit non-zero if files are never found

### ISSUE THREAD

**Issue by lgannoaa** [NOAA-EMC/EMC_verif-global#91]
The verify job currently does not exit with a non-zero error code if files are missing. data_check_gfs.sh correctly exits with a non-zero code, but the calling script does not pass that along.

This issue ticket is referenced on global-workflow issue 507:
https://github.com/NOAA-EMC/global-workflow/issues/507

**Comment by malloryprow** [comment]
@lgannoaa EMC_verif-global runs in the gfsmetp jobs. Not the verify jobs.

**Comment by lgannoaa** [comment]
Thank you @malloryprow for clarify the script in question does not belong to this repo. Close issue,
